#!/bin/bash
dot_input=""
lastoutput="poprzedni output"
output=""

for asid in $(sqlite3 asroute.sqlite "SELECT id FROM 'AS'"); do
	for ROW in $(sqlite3 asroute.sqlite "SELECT lol.asn as prevasn, rotfl.asn as asnumber, prev_as_in_cidr  FROM ASBadanie asb left join 'AS' lol on (asb.id_prev_as=lol.id) left join 'AS' rotfl on (asb.id_as=rotfl.id) where id_as=$asid;"); do
		prevasn=`echo $ROW | awk '{split($0,a,"|"); print a[1]}'`
		asnumber=`echo $ROW | awk '{split($0,a,"|"); print a[2]}'`
		cidr=`echo $ROW | awk '{split($0,a,"|"); print a[3]}'`
	      
		if [[ "$cidr" == 1 ]]; then
		    color="[color=\"red\"]"
		else
		    color="[color=\"blue\"]"
		fi

		pattern="*"
		if [[ ! -z "$prevasn" && ! ("$prevasn" == "$pattern" || "$asnumber" == "$pattern") ]]
		then
			output="$prevasn -> $asnumber $color;"
			if [[ "$output" != "$lastoutput" ]]
			then
				dot_input="$dot_input\n$(echo -e "$output")"
			fi
		fi
		lastoutput=$output
	done
done
dot_input="$(echo -e "$dot_input" | sort | uniq)"
dot_input="$(echo -e "digraph G {")\n$dot_input\n$(echo -e "}")"
echo -e "$dot_input" | dot -Tpng:cairo:gd -o graf.png
echo -e "Graph saved to graf.png"
